---
# tasks file for ruby
- name: Check if ruby is already installed
  become_user: "{{ working_user }}"
  ansible.builtin.shell:
    cmd: bash -lc "ruby -v | grep -oP '^ruby \d{1}.\d{1}.\d{1}' | cut -f 2 -d ' '"
  register: ruby_install_check
  changed_when: false

- name: Install ruby with rbenv
  become_user: "{{ working_user }}"
  ansible.builtin.shell:
    cmd: bash -lc "rbenv install {{ ruby_version }}"
  when: ruby_install_check.stdout != ruby_version

- name: Set the global ruby version
  become_user: "{{ working_user }}"
  ansible.builtin.shell:
    cmd: bash -lc "rbenv global {{ ruby_version }}"
  when: ruby_install_check.stdout != ruby_version
