---
# tasks file for rbenv
- name: Install rbenv
  become_user: "{{ working_user }}"
  ansible.builtin.git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv

- name: Set the global rbenv path (add ~/.rebenv/bin)
  become_user: "{{ working_user }}"
  ansible.builtin.lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    state: present

- name: Set the global rbenv path (add ~/.rebenv/shims)
  become_user: "{{ working_user }}"
  ansible.builtin.lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/shims:$PATH"'
    state: present

- name: Set the global rbenv path (init rbenv)
  become_user: "{{ working_user }}"
  ansible.builtin.lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    state: present

- name: Reload bash_profile
  become_user: "{{ working_user }}"
  ansible.builtin.shell:
    cmd: source /home/ec2-user/.bash_profile
  changed_when: false

- name: Install dependencies for ruby-build
  ansible.builtin.yum:
    name:
      - autoconf
      - patch
      - bzip2
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - zlib-devel
      - gdbm-devel
      - ncurses-devel
    state: present

- name: Install ruby-build plugin
  become_user: "{{ working_user }}"
  ansible.builtin.git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
